credentials:
  usernames:
    adminuser:
      name: Admin User
      password: "12345"  # hash bcrypt
      roles:
        - admin

cookie:
  name: my_news_app_cookie
  key: some_random_signature_key_12345
  expiry_days: 0
